exp_name: ""  # This needs to be filled in with the actual script name at runtime
seed: 1
torch_deterministic: true
cuda: true
track: false
wandb_project_name: "cleanRL"
wandb_entity: null
capture_video: false
env_id: "CartPole-v1"
total_timesteps: 500000
learning_rate: 2.5e-4
num_envs: 1
num_steps: 128
anneal_lr: true
gamma: 0.99
gae_lambda: 0.95
num_minibatches: 4
update_epochs: 4
norm_adv: true
clip_coef: 0.2
clip_vloss: true
ent_coef: 0.01
vf_coef: 0.5
max_grad_norm: 0.5
target_kl: null
